---
- name: docker_host_facts example
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - debug: msg="{{ ansible_host }}"

    - name: Get Docker Engine facts
      community.docker.docker_host_info:
        docker_host: '{{ ansible_host }}'
        tls: true
      register: output

    - name: Print output
      debug: msg="{{ output }}"
